In [1]:
import numpy as np


In [2]:
array_bir = np.array([10, 20, 30, 40, 50])

In [3]:
print("Bir boyutlu array boyutu:", array_bir.ndim)

Bir boyutlu array boyutu: 1


In [4]:
print("Bir boyutlu array eleman sayısı:", array_bir.size)


Bir boyutlu array eleman sayısı: 5


In [5]:
array_iki = np.array([[10, 20, 30], [40, 50, 60]])

In [6]:
print("İki boyutlu array boyutu:", array_iki.ndim)

İki boyutlu array boyutu: 2


In [7]:
print("İki boyutlu array eleman sayısı:", array_iki.size)

İki boyutlu array eleman sayısı: 6


In [8]:
print("İki boyutlu array satır-sütun:", array_iki.shape)

İki boyutlu array satır-sütun: (2, 3)


In [9]:
array_uc = np.array([[[10, 20], [30, 40]], [[50, 60], [70, 80]]])

In [10]:
print("Üç boyutlu array boyutu:", array_uc.ndim)

Üç boyutlu array boyutu: 3


In [11]:
print("Üç boyutlu array eleman sayısı:", array_uc.size)

Üç boyutlu array eleman sayısı: 8


In [12]:
print("Üç boyutlu array boyut bilgisi:", array_uc.shape)

Üç boyutlu array boyut bilgisi: (2, 2, 2)


In [13]:
print("Bir boyutlu array indexleme:", array_bir[2])

Bir boyutlu array indexleme: 30


In [14]:
print("İki boyutlu array indexleme:", array_iki[1, 2])

İki boyutlu array indexleme: 60


In [15]:
print("Üç boyutlu array indexleme:", array_uc[1, 0, 1])

Üç boyutlu array indexleme: 60


In [16]:
print("Bir boyutlu array dilimleme:", array_bir[1:4])

Bir boyutlu array dilimleme: [20 30 40]


In [17]:
print("İki boyutlu array dilimleme:", array_iki[:, 1:])

İki boyutlu array dilimleme: [[20 30]
 [50 60]]


In [18]:
print("Üç boyutlu array dilimleme:", array_uc[1, :, :])

Üç boyutlu array dilimleme: [[50 60]
 [70 80]]


In [20]:
sifirlar_array = np.zeros((2, 3))

In [21]:
print("Sıfırlardan oluşan array:\n", sifirlar_array)

Sıfırlardan oluşan array:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [22]:
birler_array = np.ones((2, 3))

In [23]:
print("Birlerden oluşan array:\n", birler_array)

Birlerden oluşan array:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [24]:
birlesik_array = np.concatenate((sifirlar_array, birler_array), axis=1)

In [25]:
print("Birleştirilmiş array:\n", birlesik_array)

Birleştirilmiş array:
 [[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]
